### ISSUE TITLE
1.19.2 Crash when holding the Advanced Battery

### ISSUE THREAD

**Issue by Gamerbolts** [Pitan76/AdvancedReborn#1]
Hello, I am creating a rather large modpack and while testing out your mod I was giving myself items from the creative menu and crashed when I gave myself the Advanced Battery. Here are the logs. Any help is appreciated Thank you!

[crash-2022-11-29_15.15.41-server.txt](https://github.com/Pitan76/AdvancedReborn/files/10117378/crash-2022-11-29_15.15.41-server.txt)
[crash-2022-11-29_15.15.52-client.txt](https://github.com/Pitan76/AdvancedReborn/files/10117380/crash-2022-11-29_15.15.52-client.txt)
[latest.log](https://github.com/Pitan76/AdvancedReborn/files/10117382/latest.log)

**Comment by PTOM76** [comment]
Thank you for your report.
I forgot to make TR correspond to 5.4.0.
