### ISSUE TITLE
[1.20.1] どのマシンも開くとクラッシュします

### ISSUE THREAD

**Issue by windy664** [Pitan76/AdvancedReborn#16]
[crash-2024-02-17_22.33.50-client.txt](https://github.com/Pitan76/AdvancedReborn/files/14319194/crash-2024-02-17_22.33.50-client.txt)
最新の MOD では、どのマシンでも GUI を開くと、ゲームが直接クラッシュします！

**Comment by PTOM76** [comment]
I'm sorry, but the transition to the 2.x.x series has not yet been completed, so please use the 1.x.x series for a while.

**Comment by PTOM76** [comment]
ご報告ありがとうございます。
了解しました。調査します。
Thank you for your report.
I got it. I'll investigate.

**Comment by PTOM76** [comment]
It may have been fixed in 1.2.7, but please check. MCPitanLib must also be updated.
