### ISSUE TITLE
1.20.1 Crash

### ISSUE THREAD

**Issue by Gamerbolts** [Pitan76/AdvancedReborn#17]
Hello, I am getting a crash trying to get in to my modpack. It is a pretty generic crash log from the looks of it but I removed adv reborn from the pack and it ran. Here is the crashlog, thanks!

[crash-2024-02-18_12.08.37-client.txt](https://github.com/Pitan76/AdvancedReborn/files/14323778/crash-2024-02-18_12.08.37-client.txt)

**Comment by PTOM76** [comment]
thanks for your reporting! fixed from 1.2.6

**Comment by Gamerbolts** [comment]
Updated to latest version 1.2.6 and still crashed, Here is the new crashlog

[crash-2024-02-21_10.25.44-client.txt](https://github.com/Pitan76/AdvancedReborn/files/14362251/crash-2024-02-21_10.25.44-client.txt)

**Comment by PTOM76** [comment]
Please update MCPitanLib too.
