### ISSUE TITLE
1.20.4 crash

### ISSUE THREAD

**Issue by Rogenar** [Pitan76/AdvancedReborn#18]
[crash-2024-02-21_02.31.56-client.txt](https://github.com/Pitan76/AdvancedReborn/files/14352212/crash-2024-02-21_02.31.56-client.txt)
[latest.log](https://github.com/Pitan76/AdvancedReborn/files/14352213/latest.log)

**Comment by PTOM76** [comment]
Thanks for your reporting!. Fixed by v1.2.7
