### ISSUE TITLE
[1.19.2] Crashing server

### ISSUE THREAD

**Issue by itsdinkd** [Pitan76/AdvancedReborn#4]
Hi

I can't really give reproduction steps here but I noticed in my servers crash reports that advanced reborn machine caused a crash. This is in my modpack, another quality modpack 2, would like to see if we can possibly get this patched up to eliminate any future crashes for players, if possible.

https://mclo.gs/EK82EG5

**Comment by PTOM76** [comment]
https://www.curseforge.com/minecraft/mc-mods/advancedreborn/files/4390040
1.1.3 was for 1.19/1.19.1.
This is my mistake, released 1.1.6 for 1.19.2.

**Comment by PTOM76** [comment]
Thanks for your reporting!
