### ISSUE TITLE
Tech Reborn crash with Advanced Reborn in 1.20

### ISSUE THREAD

**Issue by realBritakee** [Pitan76/AdvancedReborn#9]
Describe the bug
When only using Tech Reborn and Advanced Reborn the game crashed with reason "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'advanced_reborn'!"

Steps to Reproduce

1.Make a new 1.20 Fabric 0.14.21 modpack in Curse Forge Launcher
2. Add Tech Reborn, Advanced Reborn and Reborn Core
3. Start and see

Environment:
Minecraft: 1.20
Mod Loader: Fabric 0.14.21

Logs
https://pastebin.com/bhuuavsi | Latest Log
https://pastebin.com/yzsgpUJx | Crash Report

**Comment by PTOM76** [comment]
Oops, CC: Restitched became CC: Tweaked. thank you

**Comment by PTOM76** [comment]
Fixed
